apiVersion: v1
kind: Service

metadata:
        name: service-api-gateway
        namespace: srilanka
        labels:
          env: srilanka-api

spec:
        type: NodePort
        ports:
                - port: 80
                  targetPort: 9191
        selector:
          env: srilanka-api
